### Get a list of all countries
GET localhost:8090/countries

### Get a list of all countries based on id
GET localhost:8090/countries/1


###: POST a mew country
POST localhost:8090/countries
Content-Type: application/json

{
  "countryId": 3,
  "countryTxt": "Germany",
  "isocode": "150-151"
}