### Get a list of all countries
GET localhost:8080/countries

### Get a list of all countries based on id
GET localhost:8080/countries/1


###: POST a mew country
POST localhost:8080/countries/country