### Get a list of all countries
GET localhost:8090/countries

### Get a list of all countries based on id
GET localhost:8090/countries/1


### Gets a list of all countries and its probabilites of having a terrorist attacks
GET localhost:8090/countries/probabilites