
### delete terorist attack by id
DELETE localhost:8090/terrorist_attacks/9

### delete terorist attack by id
POST http://localhost:8090/terrorist_attacks
Content-Type: application/json

{
  "date": "2023-01-15T11:30:00.000Z",
  "location": "New York",
  "target": "Building",
  "casualities": 1000,
  "country_id": 1
}

### Send PUT request with json body
PUT http://localhost:8090/terrorist_attacks/7
Content-Type: application/json

{
  "date": "2023-01-15T11:30:00.000Z",
  "location": "Praha",
  "target": "Building",
  "casualities": 1000,
  "country_id": 1
}

### GETS average casualities of terroristattacks in span of min and max casualities
GET http://localhost:8090/terrorist_attacks/casualities/averagecasulities/100/500

### GETS terrorist attacks where is lower or higher casualities than number and sort it ascendingly or descendingly
GET http://localhost:8090/terrorist_attacks/casualities/lowerorhighercasualities/lower/500/ASC

### GETS weighted average of casualities
GET http://localhost:8090/terrorist_attacks/casualities/weighted_average?weights=0.5,0.3,0.2

### GETS standard derivation of casualites from value
GET http://localhost:8090/terrorist_attacks/casualities/standarddeviationfromvalue/5
